# Generated by Django 3.0.6 on 2020-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_event_app', '0004_auto_20200529_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Guest',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
    ]
